"""
Django settings for proyecto_cbpa project.
Generated by 'django-admin startproject' using Django 5.0.7.
"""
import os
import sys
from pathlib import Path
import dj_database_url

# Detectar entorno desde variable de entorno
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')
print(f"ENTORNO DETECTADO: {ENVIRONMENT}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-z_0fz%^3k-qpra%@f0+d@iwyio^5#1bk81$oj0*l%zld7#u4&_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if ENVIRONMENT == 'development' else (os.environ.get('DEBUG', 'False') == 'True')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'cbpa-4myhy.ondigitalocean.app,intranet.cbpa.cl,localhost,127.0.0.1').split(',')

# CORS y seguridad configurados según el entorno
if ENVIRONMENT == 'production':
    # Configuración de seguridad para producción
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # CORS para producción
    CORS_ALLOWED_ORIGINS = [
        'https://intranet.cbpa.cl',
        'https://cbpa-4myhy.ondigitalocean.app',
    ]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Configuración de seguridad para desarrollo - deshabilitada completamente
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_PROXY_SSL_HEADER = None  # Desactivar completamente para desarrollo
    
    # CORS para desarrollo - permitir todo
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:8080',
        'http://127.0.0.1:8080',
    ]
    CORS_ALLOW_ALL_ORIGINS = True  # Facilita el desarrollo

ROOT_URLCONF = 'proyecto_cbpa.urls'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'web'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_cbpa.wsgi.application'

# Database
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
        )
    }
else:
    # Usar SQLite si no hay DATABASE_URL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }   

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

if ENVIRONMENT == 'production':
    STATIC_ROOT = os.getenv('STATIC_ROOT', '/workspace/staticfiles')  # Ruta en producción
    STATICFILES_DIRS = []  # No se usa en producción
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Ruta local
    STATICFILES_DIRS = []  # No necesitas incluir la carpeta 'static' de la app 'web'

# URL para servir archivos estáticos
STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DIGITALOCEAN_API_TOKEN = os.environ.get('DIGITALOCEAN_API_TOKEN', '')