# Generated by Django 5.0.7 on 2024-09-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('volunteers', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=256, null=True)),
                ('contact', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=32)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.part')),
            ],
        ),
        migrations.CreateModel(
            name='RepairAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.repair')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_code', models.CharField(max_length=32)),
                ('car_type', models.CharField(blank=True, max_length=32, null=True)),
                ('license_plate', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('technical_inspection', models.DateField()),
                ('emissions_inspection', models.DateField()),
                ('insurance', models.CharField(max_length=32)),
                ('insurance_exp_date', models.DateField()),
                ('vehicle_registration', models.DateField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.company')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vehicle'),
        ),
    ]
