# Generated by Django 5.0.7 on 2024-09-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partattachment',
            name='part',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PartAttachment',
        ),
    ]
