# Generated by Django 5.0.7 on 2024-09-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_part_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recovery_password_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recovery_password_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
