# Generated by Django 5.2 on 2025-04-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alert_serverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
