# Generated by Django 5.2 on 2025-04-26 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.company', verbose_name='Compañía asignada'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('superintendente', 'Superintendente'), ('secretario_comandancia', 'Secretario de Comandancia'), ('secretario_compania', 'Secretario de Compañía'), ('bombero', 'Bombero'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Firefighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Número de registro')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('quality', models.CharField(max_length=100, verbose_name='Calidad')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de contacto')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo personal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.company', verbose_name='Compañía')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firefighter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bombero',
                'verbose_name_plural': 'Bomberos',
                'ordering': ['company', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('relationship', models.CharField(choices=[('Familiar', 'Familiar'), ('Amigo', 'Amigo'), ('Cónyuge', 'Cónyuge'), ('Otro', 'Otro')], max_length=50, verbose_name='Parentesco')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Número de contacto')),
                ('firefighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='web.firefighter')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
            },
        ),
        migrations.CreateModel(
            name='FirefighterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificado', 'Certificado'), ('diploma', 'Diploma'), ('licencia', 'Licencia'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de documento')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('issue_date', models.DateField(verbose_name='Fecha de emisión')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('file', models.FileField(upload_to='firefighter_documents/', verbose_name='Archivo')),
                ('firefighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.firefighter')),
            ],
            options={
                'verbose_name': 'Documento de bombero',
                'verbose_name_plural': 'Documentos de bomberos',
            },
        ),
    ]
